### ISSUE TITLE
Nix package is missing `meta.mainProgram` attribute

### ISSUE THREAD

**Issue by stv0g** [mirkolenz/makejinja#154]
Output of running `lib.getExe` against the package:

```
trace: warning: getExe: Package "python3.11-makejinja-2.5.0" does not have the meta.mainProgram attribute. We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold. If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away. Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
```

**Comment by mirkolenz** [comment]
It seems that `poetry2nix` does not add `meta.mainProgram` by default. I fixed this by adding a custom meta attribute to the derivation, including a description and proper license information. Thanks for the report! The changes are available in https://github.com/mirkolenz/makejinja/releases/tag/v2.6.0 (the CI pipeline is still running and may take a few minutes to complete).

**Comment by stv0g** [comment]
Thanks :)
