### ISSUE TITLE
Support operation without `.jinja` suffix

### ISSUE THREAD

**Issue by stv0g** [mirkolenz/makejinja#155]
It would be great if makejinja could operate on all files in the input paths without selecting the rendered files based on a file suffix.

In my application, I would like to render all files irrespectively of their suffix.

**Comment by mirkolenz** [comment]
Thanks for the request, totally makes sense to add such an option. I just made the necessary changes, you can now pass an empty Jinja suffix to enforce rendering all files in the input path. The feature is are available in https://github.com/mirkolenz/makejinja/releases/tag/v2.6.0 (the CI pipeline is still running and may take a few minutes to complete).

**Comment by stv0g** [comment]
Thanks a lot Mirko! That was fast :D
