### ISSUE TITLE
`--exclude-patterns` does not support recursive globbing (`**`)

### ISSUE THREAD

**Issue by sudoBash418** [mirkolenz/makejinja#181]
Based on the default value for `--include-patterns` (`**/*`), I incorrectly assumed that `--exclude-patterns` would also support recursive globbing using `**`.

Instead, `**` is silently treated the same as `*`, because makejinja uses [`PurePath.match`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.match) to test exclude patterns (whose documentation mentions that `**` is not supported).

I'm not sure how difficult it would be to support recursive globbing, but it would be appreciated if makejinja could warn the user if they specify an exclude pattern containing `**`, to avoid confusion for anyone who runs into this limitation.

**Comment by mirkolenz** [comment]
Thank you for bringing this up! I'll have a look at the code in the coming days and add a warning message to the output (and improve the documentation of that option too).

**Comment by mirkolenz** [comment]
I added a validator to the `exclude_patterns` option. If any entry contains `**`, a warning is printed to stdout. I also documented this behavior in the manpage of `makejinja`. The changes are included in [v2.6.2](https://github.com/mirkolenz/makejinja/releases/tag/v2.6.2), feel free to test it!

**Comment by sudoBash418** [comment]
Looks good to me, thank you!
