### ISSUE TITLE
AttributeError relating to cattrs

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#200]
**Describe the bug**

It seems like the update to cattrs https://github.com/python-attrs/cattrs/releases/tag/v24.1.0 has some breaking changes here

https://github.com/onedr0p/cluster-template/discussions/1571

**Comment by mirkolenz** [comment]
Thanks for letting me know about the issue, it seems to be related to #192. As stated there, the dependency `typed-settings` has since been updated to support the breaking changes, so updating the lockfile should be sufficient to resolve the problem. Please let me know if it works for you!

**Comment by onedr0p** [comment]
I somehow missed that issue in my search, thanks for the info. I am sure this will address the problem.
