### ISSUE TITLE
Add support for more filters

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#93]
**Is your feature request related to a problem? Please describe.**

Hi again 👋

I'm looking at using makejinja to replace the Ansible playbook I created to template out a ton of files. I was relieved to find that this project pretty much checks all my boxes as a CLI tool. It's fast and has a ton of features I love like not creating the file if the whole contents of the file are wrapped in an if statement that evaluates to false. I also love how we can pass files and data-vars that get interpreted into variables.

One thing I'm lacking however is some more jinja filters. I'm sure I could use a custom loader for this but I wanted to try and keep my usage only to the CLI.

Some of these filters I'm missing  that are included in Ansible are:

- nthhost ([src](https://github.com/ansible-collections/ansible.utils/blob/main/plugins/filter/nthhost.py)) ([docs](https://docs.ansible.com/ansible/latest/collections/ansible/utils/nthhost_filter.html))
- password_hash ([src](https://github.com/ansible/ansible/blob/bf9509bf33b2675d73f4abe72bebb91815d284f5/lib/ansible/plugins/filter/core.py#L277)) ([docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/password_hash_filter.html))

It would be cool if these were supported but I understand if this maintenance would be burden to you.

Anyways I really love this tool and am trying to make it fit in with my use-cases.

Edit: I'm now seeing the docs on building a custom loader, I'll give this a shot.

**Comment by onedr0p** [comment]
I was able to make these work with a custom loader 🎉 

```python
import netaddr, bcrypt

def nthhost(value: str, query: int) -> str:
    value = netaddr.IPNetwork(value)

    try:
        nth = int(query)
        if value.size > nth:
            return str(value[nth])

    except ValueError:
        return False

    return value

def passhash(value: str) -> str:
    return bcrypt.hashpw(value.encode(), bcrypt.gensalt(rounds=10)).decode("ascii")

class Loader:
    def filters(self):
        return [nthhost, passhash]
```

I will close this issue, thanks!

**Comment by mirkolenz** [comment]
Great to hear that you were able to solve this issue using a custom loader 😄, thanks for sharing it!
