### ISSUE TITLE
Empty folders exist after templating

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#94]
**Is your feature request related to a problem? Please describe.**

I have some templates that do not render because I am not setting the `--keep-empty` flag (which is expected), however this can lead to empty folders if a template was never rendered.

Take this file in the path `./input/discord-template-notifier/app/test.yaml.j2` for example

```jinja2
{% if discord_template_notifier.enabled | default(false) %}
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
{% endif %}
```

When I use makejinja to template this to the output of `./output` I see empty folders for `discord-template-notifier/app` because that `if` statement evaluate to false

**Describe the solution you'd like**

Do not create folders if there are templates that won't get rendered to it.

**Describe alternatives you've considered**

For now I am running `find ./output -type d -empty -delete` to clean up these empty folders after running makejinja

**Comment by mirkolenz** [comment]
The tool already keeps track of all generated files and folders, so adding this should not be too much of an issue (hopefully 😄 )

Personally, I would assume that if one wants to remove empty files, empty folders should be removed as well (so this is more a bug from my point of view). Thus I would not tend to not add a new config option, but use the existing one in an effort to not have "too many" config options.

If however you have a use case that required different behavior for empty files and folders please let me know and I will reconsider this.

**Comment by mirkolenz** [comment]
I just published a new version (https://github.com/mirkolenz/makejinja/releases/tag/v2.3.4) that contains the requested changes. I added a test for empty directories and everything passes, please let me know if it works for you as well.

**Comment by onedr0p** [comment]
Sweet! Out of the house for a bit but I'll be sure to test when I'm back.

**Comment by onedr0p** [comment]
Work great, thanks for the fix!

**Comment by mirkolenz** [comment]
Great, thanks for reporting back 😃
