### ISSUE TITLE
Running makejinja strips last newlines in from files in output

### ISSUE THREAD

**Issue by onedr0p** [mirkolenz/makejinja#99]
**Describe the bug**

I usually write all my files with a trailing new line, it looks like this isn't preserved when templating out the files with makejinja. This is causing some issues in my linters because they expect a empty newline at the bottom of all files.

*To Reproduce**

Add a empty newline a the bottom of the file, then when you template it out makejinja removes that newline.

**Expected behavior**

This newline to be preserved.

**Comment by mirkolenz** [comment]
This is the expected default behavior of Jinja. You can pass `--keep-trailing-newline` to change this. Hope this helps!

**Comment by onedr0p** [comment]
You know I've looked at the `--help` so many times and somehow missed that 🤦🏼 

Thanks 🤣

**Comment by mirkolenz** [comment]
Yeah I know that feeling 😂
